name: website deployment
on: [push]
jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bucket actions
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm i
      - run: npm run build

      - name: Publish
        uses: appleboy/scp-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.KEY }}
          source: "./dist/*"
          target: "/var/www/redanthrax.dev"
